(deftheme lush
  "Created 2014-12-09.")

(custom-theme-set-faces
 'lush
 '(bold ((t (:bold t))))
 '(bold-italic ((t (:bold t))))
 '(border-glyph ((t (nil))))
 '(fringe ((t (:background "#202020"))))
 '(buffers-tab ((t (:foreground "#E0E0E0" :background "#202020"))))
 '(font-lock-builtin-face ((t (:foreground "Khaki"))))
 '(font-lock-comment-face ((t (:foreground "#2AA198" :italic t))))
 '(font-lock-constant-face ((t (:foreground "#FF951B"))))
 '(font-lock-doc-face ((t (:foreground "SlateGray"))))
 '(font-lock-doc-string-face ((t (:foreground "#FF951B"))))
 '(font-lock-string-face ((t (:foreground "#61CE3C"))))
 '(font-lock-function-name-face ((t (:foreground "#FF88FF"))))
 '(font-lock-keyword-face ((t (:foreground "#FFE329"))))
 '(font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
 '(font-lock-type-face ((t (:foreground "#82A6DF"))))
 '(font-lock-variable-name-face ((t (:foreground "#FA583F"))))
 '(font-lock-negation-char-face ((t (:foreground "#FF88FF"))))
 '(font-lock-warning-face ((t (:foreground "Pink" :bold t))))
 '(gui-element ((t (:foreground "black" :background "#D4D0C8"))))
 '(mode-line ((t (:foreground "#F0F0F0" :background "#444444" :box nil))))
 '(mode-line-highlight ((t (:foreground "#FF88FF" :box nil))))
 '(hl-line ((t (:background "#333333"))))
 '(text-cursor ((t (:foreground "black" :background "yellow"))))
 '(region ((t (:background "#284050"))))
 '(highlight ((t (:background "#222222"))))
 '(highline-face ((t (:background "SeaGreen"))))
 '(italic ((t (nil))))
 '(left-margin ((t (nil))))
 '(toolbar ((t (nil))))
 '(magit-item-highlight ((t (:inherit region))))
 '(underline ((nil (:underline nil))))
 '(default ((t (:foreground "#E0E0E0" :background "#202020")))))

(provide-theme 'lush)
